name = "Pua"
grammar = "pua"
path_suffixes = ["pua"]
line_comments = ["-- "]
autoclose_before = ";:.,=}])>"
increase_indent_pattern = "^\\s*(fn\\b.*\\)|if\\b.+|elif\\b.+|else\\b|while\\b.+|for\\b.+\\bin\\b.+|with\\b.+|try\\b|except\\b.*|finally\\b)\\s*(--.*)?$"
decrease_indent_pattern = "^\\s*(elif\\b|else\\b|except\\b|finally\\b)\\b.*$"
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["string"] },
]
