id = "pua"
name = "Pua"
version = "0.0.1"
schema_version = 1
authors = ["Levy"]
description = "Pua language support"
repository = "https://example.com/pua"
themes = []
icon_themes = ["icon_themes/pua-icons.json"]
languages = ["languages/pua", "languages/ptml"]
capabilities = []

[lib]

[grammars.pua]
repository = "file:///Users/levy/Projects/zed-grammars/pua"
rev = "main"
path = "."

[grammars.ptml]
repository = "file:///Users/levy/Projects/zed-grammars/ptml"
rev = "main"
path = "."

[language_servers.pua-lsp]
languages = ["Pua"]
